version: "3.7"
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/myapp
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: myapp_development
    networks:
      - app-network

  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
